# Generated by Django 4.2.1 on 2023-06-13 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_rename_event_status_eventstatus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventstatus",
            options={"verbose_name_plural": "Event Status"},
        ),
    ]
