# Generated by Django 4.2.1 on 2023-05-30 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_user_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="authentication.team",
            ),
        ),
    ]
