# Generated by Django 4.2.1 on 2023-06-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("epicevents", "0003_alter_contract_status_delete_statut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="epicevents.contract",
            ),
        ),
    ]
